config/routes.rb
Rails.application.routes.draw do
  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    resources :lists, only: [:index, :new, :create, :destroy] do
    end
  end

  resources :ingredients, only: [:index]
  root 'homes#index'
  devise_for :users
end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :lists
  has_many :recipes, through: :lists

  def extract_potential_to_gu
   (extract_potential - 1) * 1000
  end

  def method_missing(method_sym)
    if method_sym.to_s =~ /^is_a_(.*)?$/
      test = $1.chomp("?").capitalize
      main_class == test
    end
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :ingredient_id, presence: true
 
  def individual_gravity
    ((ingredient.extract_potential_to_gu * amount) * 0.72) / recipe.batch_size
  end

  def individual_ibu_level(gravity)
    (amount * (0.30 * boil_time) * (ingredient.alpha_acid / 100) * 7490) / (recipe.batch_size * (1 + (gravity / 0.5)))
  end

  def og_to_abv(gravity)
    (gu_to_og(gravity) - gu_to_og(gravity * ((100 - ingredient.attenuation ) / 100))) * 131
  end

  def gu_to_og(value)
    (value / 1000) + 1
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :lists
  has_many :ingredients, through: :lists

  validates :name, presence: true
  validates :batch_size, presence: true, numericality: { greater_than: 0 }
  belongs_to :user

  accepts_nested_attributes_for :lists

  def total_gravity
    @total_gravity = 0
    lists.each do |list|
      if list.ingredient.is_a_grain?
        @total_gravity += list.individual_gravity
      end
    end
    (@total_gravity / 1000) + 1
  end

  def total_ibu
    @total_ibu = 0
    lists.each do |list|
      if list.ingredient.is_a_hop?
        @total_ibu += list.individual_ibu_level(@total_gravity)
      end
    end
    @total_ibu
  end

  def total_abv
    @total_abv = 0
    lists.each do |list|
      if list.ingredient.is_a_yeast?
        @total_abv = list.og_to_abv(@total_gravity)
      end
    end
    @total_abv
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # def new

  # end

  # def create

  # end
  # private
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @list = List.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_list = List.where(recipe_id: @recipe.id).sort_by { |list| list.ingredient_id }
    @list = @recipe.lists.new(list_params)
    if @list.save
      flash[:notice] = "Ingredient Added."
      redirect_to new_recipe_list_path(@recipe)
    else
      flash.now[:notice] = @list.errors.full_messages.join("! ")
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @list = List.find(params[:id])
    @list.destroy
    redirect_to new_recipe_list_path(@recipe)
  end

  private

  def list_params
    params.require(:list).permit(
      :recipe_id, :ingredient_id, :amount, :boil_time
    )
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @list = List.new
  end

  def new
    @ingredients = Ingredient.all
    @recipe = Recipe.new
    @list = List.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      flash[:notice] = "Recipe Added."
      redirect_to recipes_path
    else
      flash[:notice] = @recipe.errors.full_messages[0]
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path(@recipe)
  end

  protected

  def recipe_params
    params.require(:recipe).permit(
      :name, :visibility, :batch_size
    )
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/grains_helper.rb
module GrainsHelper
end

app/helpers/hops_helper.rb
module HopsHelper
end

app/helpers/list_helper.rb
module ListHelper

  def calculate_gravity

   @recipe.lists.each do |list|
     if list.ingredient_id < 72
       @total_gravity += list.individual_gravity
     end
   end
     ((@total_gravity/1000) + 1).round(3)
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/yeasts_helper.rb
module YeastsHelper
end

app/views/homes/index.html.erb
<div class="background-image">
</div>
<div class="row">
  <div class="small-9 large-centered column">
    <div class="home-intro">
      <div class="font-pretty">Brau Meister</div>
      <div class="font-pretty smaller">for purrfect beer</div>
    </div>
      <%if current_user %>
  	    <div class="recipe-maker-button">
          <%= link_to 'Recipe Maker', new_recipe_path, class: "button large radius" %>
        </div>
      <% else %>    
      <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-3">
        <div class="login-to-use">
        <%= link_to "log in, get started", new_user_session_path,
          class: "button large alert" %>
        </div>
      <% end %>
    </ul>
  </div>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrauMeister</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Maven+Pro|Nunito|Berkshire+Swash' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="maker-background"></div>
  <div class="data-padding-box"></div>
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Brau Meister</a></h1>
      </li>
    </ul>
    
    <section class="top-bar-section">
      <ul class="left">
        <% if current_user %>
          <li class="name"><%= link_to 'All Recipes', recipes_path %></li>
        <% end %>
      </ul>
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div data-alert class="alert-box">
      <div class="flash flash-<%= key %>">
        <%= value %>
      </div>
    </div>  
  <%- end -%>

  
  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
  
</body>
</html>

app/views/lists/_grain_form.html.erb
<div class="row" id="grain-form">
  <div class="grain">
    <%= form_for [@recipe, @list] do |f| %>
      <h5>Grains</h5>
      <div class="row">
        <div class="small-6 columns">
          <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"Grain"), :id, :name, include_blank: "Select" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :amount %>
        </div>
        <div class="small-2 columns">
          <%= f.label "Amount(pounds)" %>
        </div>
        <div class="small-2 columns">
          <%= f.submit "Submit", class: "button tiny radius grains" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="extract">
    <%= form_for [@recipe, @list] do |f| %>
      <h5>Extracts</h5>
      <div class="row">
        <div class="small-6 columns">
          <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"Extract"), :id, :name, include_blank: "Select" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :amount %>
        </div>
        <div class="small-2 columns">
          <%= f.label "Amount(pounds)" %>
        </div>
        <div class="small-2 columns">
          <%= f.submit "Submit", class: "button tiny radius grains" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="adjunct">
    <%= form_for [@recipe, @list] do |f| %>
      <h5>Adjuncts</h5>
      <div class="row">
        <div class="small-6 columns">
          <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"Adjunct"), :id, :name, include_blank: "Select" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :amount %>
        </div>
        <div class="small-2 columns">
          <%= f.label "Amount(pounds)" %>
        </div>
        <div class="small-2 columns">
          <%= f.submit "Submit", class: "button tiny radius grains" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="sugar">
    <%= form_for [@recipe, @list] do |f| %>
      <h5>Sugars</h5>
      <div class="row">
        <div class="small-6 columns">
          <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"Sugar"), :id, :name, include_blank: "Select" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :amount %>
        </div>
        <div class="small-2 columns">
          <%= f.label "Amount(pounds)" %>
        </div>
        <div class="small-2 columns">
          <%= f.submit "Submit", class: "button tiny radius grains" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/_hop_form.html.erb
<div class="row" id="hop-form">
  <div class="america">
    <%= form_for [@recipe, @list] do |f| %>
      <h5>America</h5>
      <div class="row">
        <div class="small-4 columns">
          <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"U.S."), :id, :name, include_blank: "Select" %>
        </div>
        <div class="small-2 columns form-label">
          <%= f.label "Amount (oz)" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :amount %>
        </div>
        <div class="small-2 columns form-label">
          <%= f.label "Boil Time (minutes)" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :boil_time %>
        </div>
        <div class="small-2 columns">
          <%= f.submit "Submit", class: "button tiny radius" %>
        </div>
      </div>
    <% end %>
  </div> 
  <div class="england">
    <%= form_for [@recipe, @list] do |f| %>  
      <h5>England</h5>
      <div class="row">
        <div class="small-4 columns">
          <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"England"), :id, :name, include_blank: "Select" %>
        </div>
        <div class="small-2 columns form-label">
          <%= f.label "Amount (oz)" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :amount %>
        </div>
        <div class="small-2 columns form-label">
          <%= f.label "Boil Time (minutes)" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :boil_time %>
        </div>
        <div class="small-2 columns">
          <%= f.submit "Submit", class: "button tiny radius" %>
        </div>
      </div>
    <% end %>
  </div> 
  <div class="australia">
    <%= form_for [@recipe, @list] do |f| %>  
      <h5>Australia</h5>
      <div class="row">
        <div class="small-4 columns">
          <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"Australia"), :id, :name, include_blank: "Select" %>
        </div>
        <div class="small-2 columns form-label">
          <%= f.label "Amount (oz)" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :amount %>
        </div>
        <div class="small-2 columns form-label">
          <%= f.label "Boil Time (minutes)" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :boil_time %>
        </div>
        <div class="small-2 columns">
          <%= f.submit "Submit", class: "button tiny radius" %>
        </div>
      </div>
    <% end %>
  </div> 
  <div class="germany">
    <%= form_for [@recipe, @list] do |f| %>  
      <h5>Germany</h5>
      <div class="row">
        <div class="small-4 columns">
          <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"Germany"), :id, :name, include_blank: "Select" %>
        </div>
        <div class="small-2 columns form-label">
          <%= f.label "Amount (oz)" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :amount %>
        </div>
        <div class="small-2 columns form-label">
          <%= f.label "Boil Time (minutes)" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :boil_time %>
        </div>
        <div class="small-2 columns">
          <%= f.submit "Submit", class: "button tiny radius" %>
        </div>
      </div>
    <% end %>
  </div> 
  <div class="czech">
    <%= form_for [@recipe, @list] do |f| %>  
      <h5>Czech Republic</h5>
      <div class="row">
        <div class="small-4 columns">
          <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"Czech Republic"), :id, :name, include_blank: "Select" %>
        </div>
        <div class="small-2 columns form-label">
          <%= f.label "Amount (oz)" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :amount %>
        </div>
        <div class="small-2 columns form-label">
          <%= f.label "Boil Time (minutes)" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :boil_time %>
        </div>
        <div class="small-2 columns">
          <%= f.submit "Submit", class: "button tiny radius" %>
        </div>
      </div>
    <% end %>
  </div> 
  <div class="japan">
    <%= form_for [@recipe, @list] do |f| %>  
      <h5>Japan</h5>
      <div class="row">
        <div class="small-4 columns">
          <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"Japan"), :id, :name, include_blank: "Select" %>
        </div>
        <div class="small-2 columns form-label">
          <%= f.label "Amount (oz)" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :amount %>
        </div>
        <div class="small-2 columns form-label">
          <%= f.label "Boil Time (minutes)" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :boil_time %>
        </div>
        <div class="small-2 columns">
          <%= f.submit "Submit", class: "button tiny radius" %>
        </div>
      </div>
    <% end %>
  </div> 
  <div class="zealand">
    <%= form_for [@recipe, @list] do |f| %>  
      <h5>New Zealand</h5>
      <div class="row">
        <div class="small-4 columns">
          <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"New Zealand"), :id, :name, include_blank: "Select" %>
        </div>
        <div class="small-2 columns form-label">
          <%= f.label "Amount (oz)" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :amount %>
        </div>
        <div class="small-2 columns form-label">
          <%= f.label "Boil Time (minutes)" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :boil_time %>
        </div>
        <div class="small-2 columns">
          <%= f.submit "Submit", class: "button tiny radius" %>
        </div>
      </div>
    <% end %>
  </div> 
  <div class="slovenia">
    <%= form_for [@recipe, @list] do |f| %>  
      <h5>Slovenia</h5>
      <div class="row">
        <div class="small-4 columns">
          <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"Slovenia"), :id, :name, include_blank: "Select" %>
        </div>
        <div class="small-2 columns form-label">
          <%= f.label "Amount (oz)" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :amount %>
        </div>
        <div class="small-2 columns form-label">
          <%= f.label "Boil Time (minutes)" %>
        </div>
        <div class="small-2 columns">
          <%= f.text_field :boil_time %>
        </div> 
        <div class="small-2 columns">
          <%= f.submit "Submit", class: "button tiny radius" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/_yeast_form.html.erb
<div class="row" id="yeast-form">
  <div class="weisse">
    <div class="row">
    <%= form_for [@recipe, @list] do |f| %>
      <h5>Weisse</h5>
      <div class="small-8 columns">
      <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"Weisse"), :id, :name, include_blank: "Select" %>
      </div>
      <div class="small-2 columns">
      <%= f.submit "Submit", class: "button tiny radius" %>
      </div>
    <% end %>
    </div>
  </div>
  <div class="lager">
    <div class="row">
      <%= form_for [@recipe, @list] do |f| %>
      <h5>Lager</h5>
      <div class="small-8 columns">
        <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"Lager"), :id, :name, include_blank: "Select" %>
      </div>
      <div class="small-2 columns">
        <%= f.submit "Submit", class: "button tiny radius" %>
      </div>
    <% end %>

    </div>
  </div>
  <div class="ale">
    <div class="row">
      <%= form_for [@recipe, @list] do |f| %>
      <h5>Ale</h5>
      <div class="small-8 columns">
        <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"Ale"), :id, :name, include_blank: "Select" %>
      </div>
      <div class="small-2 columns">
        <%= f.submit "Submit", class: "button tiny radius" %>
      </div>
    <% end %>

    </div>
  </div>
  <div class="belgian">
    <div class="row">
      <%= form_for [@recipe, @list] do |f| %>
      <h5>Belgian Ale</h5>
      <div class="small-8 columns">
        <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"Belgian Ale"), :id, :name, include_blank: "Select" %>
      </div>
      <div class="small-2 columns">
        <%= f.submit "Submit", class: "button tiny radius" %>
      </div>
      <% end %>
    </div>
  </div>
  <div class="sour">
    <div class="row">
    <%= form_for [@recipe, @list] do |f| %>
      <h5>Sour</h5>
      <div class="small-8 columns">
        <%= f.collection_select :ingredient_id, Ingredient.where(sub_type:"Sour"), :id, :name, include_blank: "Select" %>
      </div>
      <div class="small-2 columns">
        <%= f.submit "Submit", class: "button tiny radius" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="row">
  <div class="large-2 column not-home-page side-bar">
    <ul class="side-nav">
      <li id="vital-stats"><h4>Vital Statistics</h4></li>
      <li>Size: <%= @recipe.batch_size %> Gallons</li>
      <li>
        OG: <%= @recipe.total_gravity.round(3) %>
      </li>
      <li>
        IBU: <%= @recipe.total_ibu.round(1) %>
      </li>
      <li>
        ABV: <%= @recipe.total_abv.round(2) %>%
      </li>
    </ul>
  </div>
  <div class="large-10 column not-home-page">
    <h2><%= @recipe.name %></h2>
    <h5>Build your recipe!</h5>
    <% if current_user %>
      <div class="instructions-body">
        <ul class="accordion" data-accordion>
          <li class="accordion-navigation" id="grain-tab">
            <a href="#panel1a">Grains</a>
            <div id="panel1a" class="content">
              <%= render "grain_form" %>
            </div>
          </li>
          <li class="accordion-navigation" id="hop-tab">
            <a href="#panel2a">Hops</a>
            <div id="panel2a" class="content">
              <%= render "hop_form" %>
            </div>
          </li>
          <li class="accordion-navigation" id="yeast-tab">
            <a href="#panel3a">Yeast</a>
            <div id="panel3a" class="content">
              <%= render "yeast_form" %>
            </div>
          </li>
        </ul>
      </div>
      <h4>The List</h4>
      <h5>This is what your recipe currently contains:</h5>
      <ul>
        <% @recipe.lists.each do |list| %>
          <% if list.ingredient.is_a_grain? %>
            <li><%= list.ingredient.name %> x<%= list.amount %> lbs.
             <%= link_to "(Delete)", recipe_list_path(@recipe, list), method: :delete %>
            </li>
          <% elsif list.ingredient.is_a_hop? %>
            <li><%= list.ingredient.name %> x<%= list.amount %> oz.
            <%= link_to "(Delete)", recipe_list_path(list.recipe_id, list), method: :delete %>
            </li>
          <% else %>
            <li><%= list.ingredient.name %>
             <%= link_to "(Delete)", recipe_list_path(list.recipe_id, list), method: :delete %>
            </li> 
          <% end %>
        <% end %>
      </ul>
      <%= link_to "Done", recipes_path, class: "button radius", id: "End" %>
    <% else %>
      <h2> You must sign in to view this page! </h2>
    <% end %>
  </div>
</div>

app/views/recipes/index.html.erb
  <div class="row recipe-maker-button">
    <%= link_to 'Recipe Maker', new_recipe_path, class: "button large radius" %>
  </div>
  <div class="row not-home-page">
    <table class="your-recipes">
      <h3> Your Recipes </h3>
      <thead>
        <tr>
          <th width="225">Recipe name</th>
          <th width="125">Batch Size</th>
          <th width="125">ABV</th>
          <th width="125">IBU</th>
          <th width="125">OG</th>
          <th width="125">Remove Recipe</th>
        </tr>
      </thead>
      <tbody>
        <% @recipes.where(user_id: current_user.id).each do |recipe| %>
          <tr>
            <td>
              <%= link_to recipe.name, new_recipe_list_path(recipe.id) %>
            </td>
            <td><%= recipe.batch_size %> gallons </td>
            <td> 
              <% @total_gravity = 0 %>
              <% recipe.lists.each do |list| %>
                <% if list.ingredient_id < 72 %>
                  <% @total_gravity += list.individual_gravity %>
                <% end %>
              <% end %>
              OG: <%= ((@total_gravity/1000) + 1).round(3) %>
            </td>
            <td> 
              <% @total_ibu = 0 %>
              <% recipe.lists.each do |list| %>
                <% if list.ingredient_id > 71  && list.ingredient_id < 119 %>
                  <% @total_ibu += list.individual_ibu_level(@total_gravity) %>
                <% end %>
              <% end %>
            IBU: <%= @total_ibu.round(1) %>
            </td>
            <td>
              <% @total_abv = 0 %>
              <% recipe.lists.each do |list| %>
                <% if list.ingredient_id > 118 %>
                  <% @total_abv = list.og_to_abv(@total_gravity) %>
                <% end %>
              <% end %>
              ABV: <%= @total_abv.round(2) %>%
            </td>
            <td> <%= link_to "(Delete)", recipe_path(recipe.id), method: :delete %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>  

app/views/recipes/new.html.erb
<div class="maker-background"></div>
<div class="row not-home-page recipe-maker-button">
  <h2>Build your recipe!</h2>
  <% if current_user %>
  <% unless @recipe.name != nil  %>
    <%= form_for [@recipe]  do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :batch_size %>
      <%= f.text_field :batch_size %>
      <%= f.submit "Add Recipe", class: "button radius" %>
    <% end %> 
  <% end %>
  <% else %>
    <h2> You must sign in to view this page! </h2>
  <% end %>
</div>